
const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');

// ── Config ──────────────────────────────────────────────────────────────────
const PORT = 54321;

// Read keys from .env file
function loadEnv() {
    const env = {};
    try {
        const envPath = path.join(__dirname, '.env');
        if (fs.existsSync(envPath)) {
            const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
            for (const line of lines) {
                const match = line.match(/^([^=]+)\s*=\s*"?([^"]+)"?/);
                if (match) env[match[1].trim()] = match[2].trim();
            }
        }
    } catch (_) {}
    return env;
}

const env = loadEnv();
const RAPIDAPI_KEY = env.RAPIDAPI_KEY || '';
const FIRECRAWL_API_KEY = env.FIRECRAWL_API_KEY || '';
const GEMINI_API_KEY = env.GEMINI_API_KEY || '';

const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// ── Generic HTTPS POST helper ────────────────────────────────────────────────
function httpsPost(hostname, path, headers, body) {
    return new Promise((resolve, reject) => {
        const options = { hostname, path, method: 'POST', headers };
        const req = https.request(options, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try { resolve(JSON.parse(data)); }
                catch (e) { reject(new Error(`JSON parse error: ${data.slice(0, 200)}`)); }
            });
        });
        req.on('error', reject);
        req.write(JSON.stringify(body));
        req.end();
    });
}

// ── Generic HTTPS GET helper ─────────────────────────────────────────────────
function httpsGet(hostname, path, headers) {
    return new Promise((resolve, reject) => {
        const options = { hostname, path, method: 'GET', headers };
        const req = https.request(options, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try { resolve(JSON.parse(data)); }
                catch (e) { reject(new Error(`JSON parse error: ${data.slice(0, 200)}`)); }
            });
        });
        req.on('error', reject);
        req.end();
    });
}

// ── Gemini AI Helper ─────────────────────────────────────────────────────────
async function callGemini(systemPrompt, userMessage, history = []) {
    if (!GEMINI_API_KEY) throw new Error('GEMINI_API_KEY missing');
    
    console.log(`[Gemini] Request: "${userMessage.slice(0, 40)}..."`);
    
    const contents = [];
    
    // Convert history
    history.forEach(msg => {
        const role = msg.role === 'assistant' ? 'model' : 'user';
        if (contents.length > 0 && contents[contents.length - 1].role === role) {
            contents[contents.length - 1].parts[0].text += "\n" + msg.content;
        } else {
            contents.push({ role, parts: [{ text: msg.content }] });
        }
    });

    // Add current message
    if (contents.length > 0 && contents[contents.length - 1].role === 'user') {
        contents[contents.length - 1].parts[0].text += "\n" + userMessage;
    } else {
        contents.push({ role: 'user', parts: [{ text: userMessage }] });
    }

    // Injection of system prompt into the first user message for MAXIMUM compatibility
    const firstUser = contents.find(c => c.role === 'user');
    if (firstUser) {
        firstUser.parts[0].text = `[SYSTEM INSTRUCTION]: ${systemPrompt}\n\n[USER]: ${firstUser.parts[0].text}`;
    }

    const body = {
        contents: contents,
        generationConfig: { temperature: 0.7, maxOutputTokens: 2048 }
    };

    // Using v1 and gemini-1.5-flash for maximum stability on any key
    const apiPath = `/v1/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;
    
    const response = await httpsPost('generativelanguage.googleapis.com', apiPath, { 'Content-Type': 'application/json' }, body);
    
    if (response.error) {
        console.error('[Gemini] API Error Response:', JSON.stringify(response.error, null, 2));
        throw new Error(`Gemini API Error: ${response.error.message} (${response.error.status || 'Unknown status'})`);
    }

    const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
        console.error('[Gemini] No candidates in response:', JSON.stringify(response, null, 2));
        throw new Error('No response generated by AI');
    }
    
    console.log('[Gemini] Success');
    return text;
}

// ── Normalise utilities ──────────────────────────────────────────────────────
function normaliseLocation(raw) {
    if (!raw) return 'Remote';
    const l = raw.toLowerCase();
    if (l.includes('remote')) return 'Remote';
    if (l.includes('hybrid')) return 'Hybrid';
    return raw.replace(/,?\s*(united states|usa|us|uk|india)/gi, '').trim() || raw;
}

function normaliseType(raw) {
    if (!raw) return 'JOB';
    const l = raw.toLowerCase();
    if (l.includes('intern')) return 'INTERNSHIP';
    return 'JOB';
}

function isFresherRelevant(title, description) {
    const freshKeys = ['intern', 'fresher', 'graduate', 'entry level', 'entry-level', 'junior', 'trainee', 'campus', 'college'];
    const haystack = `${title} ${description}`.toLowerCase();
    return freshKeys.some(k => haystack.includes(k));
}

// ── Data Sources ─────────────────────────────────────────────────────────────
async function fetchCommudle() {
    if (!FIRECRAWL_API_KEY) return [];
    try {
        const data = await httpsPost('api.firecrawl.dev', '/v1/scrape', { 'Authorization': `Bearer ${FIRECRAWL_API_KEY}`, 'Content-Type': 'application/json' }, { url: 'https://www.commudle.com/explore/events', formats: ['extract'], extract: { prompt: 'Extract a list of upcoming tech events with title, organizer, and link. Focus on Indian communities.' } });
        return (Object.values(data.data?.extract || {}).find(val => Array.isArray(val)) || []).map((item, i) => ({ id: `commudle-${i}-${Date.now()}`, title: item.title || 'Tech Event', companyOrOrganizer: item.organizer || 'Commudle', type: 'EVENT', location: 'India', applyLink: item.link || '#', analysis: 'Local tech meetups and community events.', matchScore: 85, platform: 'Commudle' }));
    } catch (_) { return []; }
}

async function fetchTownscript() {
    if (!FIRECRAWL_API_KEY) return [];
    try {
        const data = await httpsPost('api.firecrawl.dev', '/v1/scrape', { 'Authorization': `Bearer ${FIRECRAWL_API_KEY}`, 'Content-Type': 'application/json' }, { url: 'https://www.townscript.com/in/india/technology-events', formats: ['extract'], extract: { prompt: 'Extract a list of technology events with title, organizer, and link.' } });
        return (Object.values(data.data?.extract || {}).find(val => Array.isArray(val)) || []).map((item, i) => ({ id: `townscript-${i}-${Date.now()}`, title: item.title || 'Tech Event', companyOrOrganizer: item.organizer || 'Townscript', type: 'EVENT', location: 'India', applyLink: item.link || '#', analysis: 'Workshops, seminars and conferences.', matchScore: 80, platform: 'Townscript' }));
    } catch (_) { return []; }
}

async function fetchActiveJobsDB(query) {
    try {
        const data = await httpsGet('active-jobs-db.p.rapidapi.com', `/active-ats-1h?offset=0&title_filter=${encodeURIComponent(query || 'intern')}&limit=20`, { 'X-RapidAPI-Key': RAPIDAPI_KEY, 'X-RapidAPI-Host': 'active-jobs-db.p.rapidapi.com' });
        return (Array.isArray(data) ? data : (data.data || data.jobs || [])).map((job, i) => ({ id: `ajdb-${i}-${Date.now()}`, title: job.title || '', companyOrOrganizer: job.company || 'Company', type: normaliseType(job.employment_type || ''), location: normaliseLocation(job.location || ''), applyLink: job.url || '#', analysis: (job.description || '').slice(0, 200) + '...', matchScore: 75, platform: 'ActiveJobs' }));
    } catch (_) { return []; }
}

async function fetchJSearch(query) {
    try {
        const data = await httpsGet('jsearch.p.rapidapi.com', `/search?query=${encodeURIComponent(query || 'intern')} in India&num_pages=1`, { 'X-RapidAPI-Key': RAPIDAPI_KEY, 'X-RapidAPI-Host': 'jsearch.p.rapidapi.com' });
        return (data.data || []).map((job, i) => ({ id: `jsearch-${i}-${Date.now()}`, title: job.job_title || '', companyOrOrganizer: job.employer_name || 'Company', type: normaliseType(job.job_employment_type || ''), location: normaliseLocation(job.job_city || 'India'), applyLink: job.job_apply_link || '#', analysis: (job.job_description || '').slice(0, 200) + '...', matchScore: 72, platform: 'JSearch' }));
    } catch (_) { return []; }
}

function deduplicate(list) {
    const seen = new Set();
    return list.filter(item => { if (!item.applyLink || item.applyLink==='#' || seen.has(item.applyLink)) return false; seen.add(item.applyLink); return true; });
}

// ── Server ───────────────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
    if (req.method === 'OPTIONS') { res.writeHead(204, corsHeaders); res.end(); return; }
    if (req.method !== 'POST') { res.writeHead(404, corsHeaders); res.end(); return; }

    let body = '';
    req.on('data', chunk => body += chunk.toString());
    req.on('end', async () => {
        try {
            const payload = JSON.parse(body || '{}');
            
            if (req.url.includes('/fetch-opportunities')) {
                const results = await Promise.all([fetchActiveJobsDB(payload.query), fetchJSearch(payload.query), fetchCommudle(), fetchTownscript()]);
                let all = deduplicate(results.flat());
                if (!payload.query) all = all.filter(o => o.type==='EVENT' || isFresherRelevant(o.title, o.analysis));
                all.sort((a,b) => (a.type==='EVENT' ? -1 : (b.type==='EVENT' ? 1 : b.matchScore-a.matchScore)));
                res.writeHead(200, { ...corsHeaders, 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ success: true, opportunities: all }));
            }
            else if (req.url.includes('/ats-analyze')) {
                const sys = "You are an ATS expert. Analyze and return ONLY JSON.";
                const user = `Resume:\n${payload.resumeText}\nJD:\n${payload.jobDescription || 'N/A'}\nFormat: {overallScore, jobFitAnalysis, fitVerdict, sections:[], keywords:{found:[], missing:[]}, improvements:[], strengths:[]}`;
                const ai = await callGemini(sys, user);
                res.writeHead(200, { ...corsHeaders, 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ success: true, analysis: JSON.parse(ai.replace(/```json\n?|```/g, '').trim()) }));
            }
            else if (req.url.includes('/analyze-resume')) {
                const sys = "Extract profile. Return ONLY JSON: {skills:[], experienceLevel, domain, searchQuery}.";
                const ai = await callGemini(sys, payload.resumeText);
                const prof = JSON.parse(ai.replace(/```json\n?|```/g, '').trim());
                const results = await Promise.all([fetchActiveJobsDB(prof.searchQuery), fetchJSearch(prof.searchQuery), fetchCommudle(), fetchTownscript()]);
                res.writeHead(200, { ...corsHeaders, 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ success: true, ...prof, opportunities: deduplicate(results.flat()).slice(0, 8) }));
            }
            else if (req.url.includes('/study-chat')) {
                const sys = "You are 'Study Buddy'. Respond in English only.";
                const ai = await callGemini(sys, payload.message, payload.conversationHistory);
                res.writeHead(200, { ...corsHeaders, 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ message: ai }));
            }
            else { res.writeHead(404, corsHeaders); res.end(); }
        } catch (err) {
            console.error('[Proxy] Error:', err.message);
            res.writeHead(500, corsHeaders);
            res.end(JSON.stringify({ error: err.message }));
        }
    });
});

server.listen(PORT, () => console.log(`🚀 CareerCampus Proxy at http://localhost:${PORT}`));
