import { callGemini, deduplicate, normaliseLocation, normaliseType, URL_PATTERNS, extractId } from './utils.js';

function formatKeyword(kw) {
    if (!kw) return 'tech';
    return kw.trim().replace(/\s+/g, '-').toLowerCase();
}

async function fetchJSearch(query, RAPIDAPI_KEY) {
    if (!RAPIDAPI_KEY) return [];
    try {
        const url = `https://jsearch.p.rapidapi.com/search?query=${encodeURIComponent(query || 'intern')} in India&num_pages=1`;
        const response = await fetch(url, { headers: { 'X-RapidAPI-Key': RAPIDAPI_KEY, 'X-RapidAPI-Host': 'jsearch.p.rapidapi.com' } });
        const data = await response.json();
        return (data.data || []).map((j, i) => {
            const platform = j.employer_website?.includes('linkedin') ? 'linkedin' : (j.employer_website?.includes('glassdoor') ? 'glassdoor' : 'indeed');
            return {
                id: extractId(j.job_apply_link, platform) || `js-${i}-${Date.now()}`,
                title: j.job_title || '',
                companyOrOrganizer: j.employer_name || 'Company',
                type: normaliseType(j.job_employment_type || ''),
                location: normaliseLocation(j.job_city || 'India'),
                applyLink: j.job_apply_link || j.job_google_link || '#',
                analysis: (j.job_description || '').slice(0, 150) + '...',
                matchScore: 85,
                platform: platform
            };
        });
    } catch (_) { return []; }
}

async function generateAllPlatformsFromGemini(prof, URL_PATTERNS) {
    console.log(`[Gemini] Deep Synthesis: Generating realistic data for ALL 32 platforms...`);
    const prompt = `You are a Live Opportunty Aggregator AI. 
    You have a user profile:
    Skills: ${prof.skills.join(', ')}
    Experience: ${prof.experienceLevel}
    
    You must generate EXACTLY 1 highly realistic, customized opportunity record for EACH platform in the provided URL_PATTERNS.
    This means you will return exactly 32 objects in the JSON array.
    Cover Jobs, Internships, Hackathons, Courses, and Events depending exactly on the platform's nature. Ensure 'type' is one of: JOB, INTERNSHIP, HACKATHON, EVENT, COURSE.
    The 'title' must sound like a real, scraped job/event (e.g., "Full-Stack Development Intern", "AI Innovators Hackathon", "Mastering React JS Certification").
    The 'applyLink' must be constructed using the strict URL pattern provided for that platform, by replacing '{keyword}' or '{role}' or '{type}' with a proper, hyphenated query (e.g., "react-developer").
    
    Return ONLY a raw JSON array of objects:
    [
      { "id": "unique-id", "platform": "internshala", "title": "...", "companyOrOrganizer": "...", "type": "INTERNSHIP", "location": "Remote", "applyLink": "https://internshala.com/...", "analysis": "1-sentence why it matches", "matchScore": 92 }
    ]`;
    
    const platformsData = JSON.stringify(URL_PATTERNS, null, 2);
    
    try {
        const response = await callGemini(prompt, platformsData);
        const jsonText = response.replace(/```json\n?|```/g, '').trim();
        return JSON.parse(jsonText);
    } catch (e) {
        console.error('[Gemini] Generation Error:', e.message);
        return [];
    }
}

export default async function handler(req, res) {
    if (req.method === 'OPTIONS') { res.status(204).json(null); return; }
    if (req.method !== 'POST') { res.status(405).json({ error: 'Method Not Allowed' }); return; }

    try {
        const { resumeText } = req.body || {};
        if (!resumeText) return res.status(400).json({ error: 'Resume text is required' });

        const RAPIDAPI_KEY = process.env.RAPIDAPI_KEY || '';

        // 1. Initial Parsing
        const systemPrompt = "Extract profile. Return ONLY JSON: {skills:[], experienceLevel, domain, searchQuery}. CRITICAL: searchQuery MUST be very concise (max 2 words).";
        const aiResponse = await callGemini(systemPrompt, resumeText);
        const prof = JSON.parse(aiResponse.replace(/```json\n?|```/g, '').trim());
        const q = prof.searchQuery || 'intern';

        console.log(`[Resume Analysis] Extracted Search Query: "${q}"`);

        // 2. Fetch Live JSearch Data & Gemini Synthesis concurrently
        const [jsearchResults, geminiOpportunities] = await Promise.all([
            fetchJSearch(q, RAPIDAPI_KEY),
            generateAllPlatformsFromGemini(prof, URL_PATTERNS)
        ]);

        let finalOpportunities = deduplicate([...jsearchResults, ...geminiOpportunities]);

        // 3. Batch Scoring via Gemini (for JSearch items that weren't generated by Gemini)
        const unScored = finalOpportunities.filter(o => !o.analysis || o.analysis.endsWith('...'));
        if (unScored.length > 0) {
            console.log(`[Gemini] Batch scoring ${unScored.length} external opportunities...`);
            const scoringPrompt = `Assign a personalized matchScore (0-100) and a short 1-sentence analysis. Return ONLY a JSON array: [{"id": "...", "matchScore": 90, "analysis": "..."}]`;
            const evalContent = `User Skills: ${prof.skills.join(', ')}\nExperience: ${prof.experienceLevel}\n\nOpportunities:\n` + unScored.map(o => `ID: ${o.id} | Title: ${o.title}`).join('\n');
            try {
                const scoreResponse = await callGemini(scoringPrompt, evalContent);
                const scoreJson = JSON.parse(scoreResponse.replace(/```json\n?|```/g, '').trim());
                const scoreMap = new Map(scoreJson.map(s => [s.id, s]));
                finalOpportunities = finalOpportunities.map(opp => {
                    const scored = scoreMap.get(opp.id);
                    return scored ? { ...opp, matchScore: scored.matchScore || opp.matchScore, analysis: scored.analysis || opp.analysis } : opp;
                });
            } catch (e) { console.error("[Gemini Scoring Error]", e.message); }
        }

        finalOpportunities.sort((a, b) => b.matchScore - a.matchScore);

        res.status(200).json({ 
            success: true, 
            ...prof, 
            opportunities: finalOpportunities 
        });
    } catch (err) {
        console.error('[Resume Analysis] Error:', err.message);
        res.status(500).json({ error: err.message });
    }
}
