export const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

export const URL_PATTERNS = {
    // 🎓 1. Internships & Fresher Jobs
    internshala: 'https://internshala.com/internships/keywords-{pathKeyword}', 
    wellfound: 'https://wellfound.com/jobs?keywords={queryKeyword}&location=India', 
    instahyre: 'https://instahyre.com/jobs/?keyword={queryKeyword}', 
    hirist: 'https://www.hirist.tech/browse-all-jobs/?q={queryKeyword}&ctype=internship',
    naukri: 'https://www.naukri.com/jobs-in-india?keyword={queryKeyword}', 
    foundit: 'https://www.foundit.in/srp?query={queryKeyword}',
    freshersworld: 'https://www.freshersworld.com/jobs/jobsearch?keyword={queryKeyword}',
    aicte: 'https://internship.aicte-india.org/internships.php',
    letsintern: 'https://letsintern.in/internships',
    yuvaintern: 'https://yuvaintern.com/internships',
    apna: 'https://apna.co/jobs?search={queryKeyword}',
    internshipwala: 'https://www.internshipwala.com/internships',

    // 🏆 2. Hackathons & Competitions
    unstop: 'https://unstop.com/hackathons?searchTerm={queryKeyword}', 
    devfolio: 'https://devfolio.co/hackathons', 
    hackerearth: 'https://www.hackerearth.com/challenges/', 
    hack2skill: 'https://hack2skill.com/hackathons',
    reskilll: 'https://reskilll.com/allhacks', 
    commudle: 'https://commudle.com/events', 

    // 🏢 3. Job Giants
    linkedin: 'https://www.linkedin.com/jobs/search/?keywords={queryKeyword}&location=India', 
    indeed: 'https://in.indeed.com/jobs?q={queryKeyword}&l=India', 
    glassdoor: 'https://www.glassdoor.co.in/Search/results.htm?keyword={queryKeyword}',
    prosple: 'https://in.prosple.com/search-jobs?keyword={queryKeyword}',
    stuintern: 'https://www.stuintern.com/internships', 

    // 📚 4. Learning/Upskilling (Courses URLs)
    nptel: 'https://nptel.ac.in/courses', 
    swayam: 'https://swayam.gov.in/explorer?keyword={queryKeyword}', 
    freecodecamp: 'https://www.freecodecamp.org/learn/', 
    youtube: 'https://www.youtube.com/results?search_query={queryKeyword}+skills+course', 
    coursera: 'https://www.coursera.org/search?query={queryKeyword}&productDifficultyLevel=Beginner',
    udemy: 'https://www.udemy.com/courses/search/?q={queryKeyword}&price=price-free',

    // 🎟️ 5. Events & Communities
    townscript: 'https://www.townscript.com/in/india/tech',
    eventbrite: 'https://www.eventbrite.com/d/india/tech-events/',
    almamater: 'https://almamater.io/events'
};

export function extractId(url, platform) {
    if (!url) return null;
    let hash = 0;
    for (let i = 0; i < url.length; i++) {
        hash = ((hash << 5) - hash) + url.charCodeAt(i);
        hash = hash & hash;
    }
    return Math.abs(hash).toString(16);
}

export async function callGemini(systemPrompt, userMessage, history = []) {
    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) throw new Error('GEMINI_API_KEY missing');

    const contents = [];
    history.forEach(msg => {
        const role = msg.role === 'assistant' ? 'model' : 'user';
        if (contents.length > 0 && contents[contents.length - 1].role === role) {
            contents[contents.length - 1].parts[0].text += "\n" + msg.content;
        } else {
            contents.push({ role, parts: [{ text: msg.content }] });
        }
    });

    if (contents.length > 0 && contents[contents.length - 1].role === 'user') {
        contents[contents.length - 1].parts[0].text += "\n" + userMessage;
    } else {
        contents.push({ role: 'user', parts: [{ text: userMessage }] });
    }

    const body = {
        system_instruction: { parts: [{ text: systemPrompt }] },
        contents: contents,
        generationConfig: { 
            temperature: 0.7, 
            maxOutputTokens: 8192,
        }
    };

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${GEMINI_API_KEY}`;
    
    const response = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
    });
    
    const data = await response.json();
    if (data.error) throw new Error(`Gemini API Error: ${data.error.message}`);

    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) throw new Error('No response generated by AI');
    
    return text;
}

export function normaliseLocation(raw) {
    if (!raw) return 'Remote';
    const l = raw.toLowerCase();
    if (l.includes('remote')) return 'Remote';
    if (l.includes('hybrid')) return 'Hybrid';
    return raw.replace(/,?\s*(united states|usa|us|uk|india)/gi, '').trim() || raw;
}

export function normaliseType(raw) {
    if (!raw) return 'JOB';
    const l = raw.toLowerCase();
    if (l.includes('intern')) return 'INTERNSHIP';
    return 'JOB';
}

export function deduplicate(list) {
    const seen = new Set();
    return list.filter(item => { 
        if (!item.applyLink || item.applyLink === '#' || seen.has(item.applyLink)) return false; 
        seen.add(item.applyLink); 
        return true; 
    });
}
