
export const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

export async function callGemini(systemPrompt, userMessage, history = []) {
    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) throw new Error('GEMINI_API_KEY missing');

    console.log(`[Gemini] Requesting analysis for: "${userMessage.slice(0, 40)}..."`);

    const contents = [];
    
    // Convert history
    history.forEach(msg => {
        const role = msg.role === 'assistant' ? 'model' : 'user';
        if (contents.length > 0 && contents[contents.length - 1].role === role) {
            contents[contents.length - 1].parts[0].text += "\n" + msg.content;
        } else {
            contents.push({ role, parts: [{ text: msg.content }] });
        }
    });

    // Add current message
    if (contents.length > 0 && contents[contents.length - 1].role === 'user') {
        contents[contents.length - 1].parts[0].text += "\n" + userMessage;
    } else {
        contents.push({ role: 'user', parts: [{ text: userMessage }] });
    }

    const body = {
        system_instruction: { parts: [{ text: systemPrompt }] },
        contents: contents,
        generationConfig: { 
            temperature: 0.7, 
            maxOutputTokens: 2048,
            topP: 0.95,
            topK: 40
        }
    };

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?key=${GEMINI_API_KEY}`;
    
    const response = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
    });
    
    const data = await response.json();
    
    if (data.error) {
        console.error('[Gemini] API Error:', JSON.stringify(data.error, null, 2));
        throw new Error(`Gemini API Error: ${data.error.message}`);
    }

    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
        console.error('[Gemini] Empty response candidates:', JSON.stringify(data, null, 2));
        throw new Error('No response generated by AI');
    }
    
    console.log('[Gemini] Success');
    return text;
}

export function normaliseLocation(raw) {
    if (!raw) return 'Remote';
    const l = raw.toLowerCase();
    if (l.includes('remote')) return 'Remote';
    if (l.includes('hybrid')) return 'Hybrid';
    return raw.replace(/,?\s*(united states|usa|us|uk|india)/gi, '').trim() || raw;
}

export function normaliseType(raw) {
    if (!raw) return 'JOB';
    const l = raw.toLowerCase();
    if (l.includes('intern')) return 'INTERNSHIP';
    return 'JOB';
}

export function isFresherRelevant(title, description) {
    const keys = ['intern', 'fresher', 'graduate', 'entry level', 'junior', 'trainee'];
    const text = `${title} ${description}`.toLowerCase();
    return keys.some(k => text.includes(k));
}

export function deduplicate(list) {
    const seen = new Set();
    return list.filter(item => { 
        if (!item.applyLink || item.applyLink === '#' || seen.has(item.applyLink)) return false; 
        seen.add(item.applyLink); 
        return true; 
    });
}
